
# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  batch: true
  branches:
    include:
      - "feature-*"
      - "develop"
      - "master"

variables:
  - group: anyrobot-global-config
  - name: BUILD_IMAGE
    value: "docker pull acr.aishu.cn/public/maven@sha256:a52afc2979dfe2c26b27da7c5f289385f79e00fe185e61aa29d8e3ea52a6a51c"
  - name: SONARQUBE_IMAGE
    value: "acr.aishu.cn/public/sonarsource/sonar-scanner-cli:4.8"
  - name: IMAGE_REGISTRY
    value: "acr.aishu.cn"
  - name: IMAGE_REPOSITORY
    value: "ar/agentcontainer"
  - name: FTP_URL
    value: "ftp-ar.aishu.cn"
  - name: FTP_USER
    value: "ftp-ar"
  - name: FTP_PWD
    value: "F64edf#s"  

resources:
  containers:
    - container: dotnet
      endpoint: ACRDockerRegistry
      image: dotnet/runtime:3.1-bullseye-slim
      
stages:
  - stage: CodeCheck
    displayName: 代码检查
    jobs:
      - job: _1CodeCheck
        displayName: 1.代码检查(UT/Lint)
        workspace:
          clean: all
        pool:
          name: telemetrySDK-pool
          demands:
            - docker
