
# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  batch: true
  branches:
    include:
      - "feature-*"
      - "develop"
      - "master"

variables:
  - group: anyrobot-global-config
  - name: IMAGE_REGISTRY
    value: "acr.aishu.cn"
  - name: IMAGE_REPOSITORY
    value: "ar/agentcontainer"
  - name: FTP_URL
    value: "ftp-ar.aishu.cn"
  - name: FTP_USER
    value: "ftp-ar"
  - name: FTP_PWD
    value: "F64edf#s"  

# resources:
#   containers:
#     - container: dotnet
#       endpoint: ACRDockerRegistry
#       image: dotnet/runtime:3.1-bullseye-slim
      
pool:
  telemetrySDK-pool

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'exporter/common/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'